### PR TITLE
Reekoh-177

### PR DESCRIPTION
**Pull request by rozzwalla**

### CODE REVIEW

**Comment by benjsicam** [comment]
Rozz, re-check this. You're supposed to have Number Data as Numbers.

**Comment by rozzwalla** [comment]
I will eat up a lot of days just doing this if I convert everything for the queclink which is not the best use of my time.

I converted to numbers/date the same code used in the converter we initially deployed.

**Comment by benjsicam** [comment]
So, who do you propose do this?

**Comment by rozzwalla** [comment]
Let's just get back to this once there are no other meaningful tasks to be done.

________________________________

**Pull request closed without merging**
